export const LOGIN_REQUESTING = "LOGIN_REQUESTING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const EMAIL_CONFIRMATION="EMAIL_CONFIRMATION";
export const EMAIL_CONFIRMATION_SUCCESS="EMAIL_CONFIRMATION_SUCCESS";
export const EMAIL_CONFIRMATION_FAILURE="EMAIL_CONFIRMATION_FAILURE";