export const REQUEST_ALL_ITEMS = "REQUEST_ALL_ITEMS";
export const REQUEST_ALL_ITEMS_SUCCESS = "REQUEST_ALL_ITEMS_SUCCESS";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const GET_CURRENT_ITEM = "GET_CURRENT_ITEM";
export const SET_FILTERED_ITEMS = "SET_FILTERED_ITEMS";
export const CREATE_ITEM = "CREATE_ITEM";
export const DELETE_ITEM="DELETE_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";

